development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: kanban_development
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

test: &test
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: kanban_test
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: kanban_production
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock


cucumber:
  <<: *test